### ISSUE TITLE
What about the result of your experiments?

### ISSUE THREAD

**Issue by LaviLiu** [InnovArul/personreid_sequential_rl#1] opened 2019-04-02 03:31 UTC
Is the reinforcement policy is power according your experiments？ Could you share your result for us?

**Comment by InnovArul** [comment] 2019-04-02 09:06
I was not able to reproduce the base paper's results. The base architecture results (Alexnet + Softmax +/ Triplet) in the paper did not coincide with my finding (the base paper had a very low number). Hence, the results of DQN from my experiments are way-off from the base paper. 

The report I wrote for this project is here : https://github.com/InnovArul/personreid_sequential_rl/blob/master/docs/project_report.pdf

**Comment by InnovArul** [comment] 2019-11-16 09:39
I hope you found solutions to your questions. I am closing this Github issue. Pl. reopen if you still have questions.

**Closed as completed by InnovArul** 2019-11-16 09:39 UTC
